### ISSUE TITLE
Building Database

### ISSUE THREAD

**Issue by Eslam3bed** [FACG2/SuperMarkets_Debt_Manager#4]
### SubTasks:
- [ ] analyzing the entities .(1h)
- [ ] draw the ER diagram.(1h)
- [ ] build the database schema.(1h)
- [ ] build and test database.(build sample database for test). ( 3 h )
   - [ ] deploy database to heroku .
