### ISSUE TITLE
Home page (search form)

### ISSUE THREAD

**Issue by Eslam3bed** [FACG2/SuperMarkets_Debt_Manager#5]
### User Story
as a super marker owner I could be able to navigate the home page either be clicking on the profile avatar or after logging in so that I can search for a customers.

### Acceptance Criteria
- [ ] build search form , result container. [Here](https://github.com/FACG2/SuperMarkets_Debt_Manager/issues/19)
- [ ] validate the search input filed before making a request. [Here](https://github.com/FACG2/SuperMarkets_Debt_Manager/issues/20)
- [ ] make xhr to send and handle requests going/coming to/from the back end on route ` /search `.[Here](https://github.com/FACG2/SuperMarkets_Debt_Manager/issues/21)
- [ ] Update the results (Dom manipulation)[Here](https://github.com/FACG2/SuperMarkets_Debt_Manager/issues/23)
- [ ] make a route on ` /search `  to preform a search operation from the customer list.[Here](https://github.com/FACG2/SuperMarkets_Debt_Manager/issues/24)
