### ISSUE TITLE
customer page 

### ISSUE THREAD

**Issue by Eslam3bed** [FACG2/SuperMarkets_Debt_Manager#9]
### User Story
As a SuperMarket owner I can see the customer page so that I can do my operations on my customers 

### Acceptance Criteria
- [ ] build the customer page. #26
- [ ] handle request for customer page ('/customer/:id'). to response with the rendered customer page. #33
- [ ] Rendering the page when data changes ,when adding the debts. #28
